#!/usr/bin/perl
# vim:ts=4:shiftwidth=4:expandtab:smartindent

# ABSTRACT: Boots up nginx.

# Contemporary RT docs only recommend fcgi for production deployment, rather
# than reproxying, so we use that.

use strict;
use warnings;

use Template;

my $hostname = $ENV{RT_HOSTNAME} // "rt.cpan.org";
my $host     = $ENV{RT_DATABASE_SERVICE_HOST} // die "Missing RT_DATABASE_SERVICE_HOST";
my $port     = $ENV{RT_DATABASE_SERVICE_PORT} // die "Missing RT_DATABASE_SERVICE_PORT";

my $tt = Template->new({ INCLUDE_PATH => "/root/tt" });

open(my $fh_nginx, ">", "/etc/nginx/sites-enabled/default") or die $!;

$tt->process("nginx_site.tt", {
    hostname    => $hostname,
    rt_app_host => $host,
    rt_app_port => $port,
}, $fh_nginx) or die $tt->error;
close $fh_nginx;

exec("/usr/sbin/nginx", "-g", "daemon off;") || die $!;
die;
