name: build

on:
  push:
    branches: main

jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: rtcpan
        uses: docker/build-push-action@v2
        with:
          context: rtcpan/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/rtcpan:latest
      -
        name: rtperl
        uses: docker/build-push-action@v2
        with:
          context: rtperl/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/rtperl:latest
      -
        name: rtfrontend
        uses: docker/build-push-action@v2
        with:
          context: rtfrontend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/rtfrontend:latest
      -
        name: rtapp
        uses: docker/build-push-action@v2
        with:
          context: rtapp/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/rtapp:latest
