name: build

on:
  push:
    branches: main

jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: rtcpan
        uses: docker/build-push-action@v2
        with:
          file: ./rtcpan/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/davel/rtcpan:latest
      -
        name: rtperl
        uses: docker/build-push-action@v2
        with:
          context: rtperl/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/davel/rtperl:latest
      -
        name: rtfrontend
        uses: docker/build-push-action@v2
        with:
          context: rtfrontend/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/davel/rtfrontend:latest
      -
        name: rtapp
        uses: docker/build-push-action@v2
        with:
          context: rtapp/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/davel/rtapp:latest
